from pathlib import Path
from typing import Iterable

import numpy as np
from numpy.typing import NDArray

from pylibhmm import _core

class EmissionDistribution(_core.EmissionDistribution): ...

class Discrete(_core.Discrete): ...
class Binomial(_core.Binomial): ...
class NegativeBinomial(_core.NegativeBinomial): ...
class Poisson(_core.Poisson): ...
class Gaussian(_core.Gaussian): ...
class Exponential(_core.Exponential): ...
class Gamma(_core.Gamma): ...
class LogNormal(_core.LogNormal): ...
class Pareto(_core.Pareto): ...
class Beta(_core.Beta): ...
class Uniform(_core.Uniform): ...
class Weibull(_core.Weibull): ...
class Rayleigh(_core.Rayleigh): ...
class StudentT(_core.StudentT): ...
class ChiSquared(_core.ChiSquared): ...

class Hmm(_core.Hmm):
    def __init__(self, num_states: int): ...
    def set_pi(self, pi) -> None: ...
    def set_trans(self, trans) -> None: ...

class ForwardBackwardCalculator(_core.ForwardBackwardCalculator):
    def __init__(self, hmm: Hmm, observations): ...
    def compute(self, observations=None): ...

class ViterbiCalculator(_core.ViterbiCalculator):
    def __init__(self, hmm: Hmm, observations): ...

class TrainingConfig(_core.TrainingConfig): ...

class BaumWelchTrainer(_core.BaumWelchTrainer):
    def __init__(self, hmm: Hmm, sequences): ...

class ViterbiTrainer(_core.ViterbiTrainer):
    def __init__(self, hmm: Hmm, sequences, config: TrainingConfig | None = None): ...

class SegmentalKMeansTrainer(_core.SegmentalKMeansTrainer):
    def __init__(self, hmm: Hmm, sequences): ...

def training_preset_fast() -> TrainingConfig: ...
def training_preset_balanced() -> TrainingConfig: ...
def training_preset_precise() -> TrainingConfig: ...

def load_hmm(filepath: str | Path): ...
def save_hmm(hmm: Hmm, filepath: str | Path) -> None: ...

__all__: list[str]
