from pathlib import Path

import numpy as np
from numpy.typing import NDArray

from pylibhmm import _core

class EmissionDistribution(_core.EmissionDistribution): ...

class Discrete(_core.Discrete): ...
class Binomial(_core.Binomial): ...
class NegativeBinomial(_core.NegativeBinomial): ...
class Poisson(_core.Poisson): ...
class Gaussian(_core.Gaussian): ...
class Exponential(_core.Exponential): ...
class Gamma(_core.Gamma): ...
class LogNormal(_core.LogNormal): ...
class Pareto(_core.Pareto): ...
class Beta(_core.Beta): ...
class Uniform(_core.Uniform): ...
class Weibull(_core.Weibull): ...
class Rayleigh(_core.Rayleigh): ...
class StudentT(_core.StudentT): ...
class ChiSquared(_core.ChiSquared): ...
class VonMises(_core.VonMises): ...

class Hmm(_core.Hmm):
    def __init__(self, num_states: int): ...
    def set_pi(self, pi) -> None: ...
    def set_trans(self, trans) -> None: ...

class ForwardBackwardCalculator(_core.ForwardBackwardCalculator):
    def __init__(self, hmm: Hmm, observations): ...
    def compute(self, observations=None): ...

class ViterbiCalculator(_core.ViterbiCalculator):
    def __init__(self, hmm: Hmm, observations): ...

class TrainingConfig(_core.TrainingConfig): ...

class BaumWelchTrainer(_core.BaumWelchTrainer):
    def __init__(self, hmm: Hmm, sequences): ...
    @property
    def last_log_probability(self) -> float: ...

class MapBaumWelchTrainer(_core.MapBaumWelchTrainer):
    def __init__(self, hmm: Hmm, sequences, pseudo_count: float = 1.0): ...

class ViterbiTrainer(_core.ViterbiTrainer):
    def __init__(self, hmm: Hmm, sequences, config: TrainingConfig | None = None): ...

class SegmentalKMeansTrainer(_core.SegmentalKMeansTrainer):
    def __init__(self, hmm: Hmm, sequences, max_iterations: int = 100): ...

def training_preset_fast() -> TrainingConfig: ...
def training_preset_balanced() -> TrainingConfig: ...
def training_preset_precise() -> TrainingConfig: ...

class ModelCriteria:
    aic: float
    bic: float
    aicc: float
    def __new__(cls, aic: float, bic: float, aicc: float) -> ModelCriteria: ...

def count_free_parameters(hmm: Hmm) -> int: ...
def compute_aic(log_likelihood: float, k: int) -> float: ...
def compute_bic(log_likelihood: float, k: int, n: int) -> float: ...
def compute_aicc(log_likelihood: float, k: int, n: int) -> float: ...
def evaluate_model(hmm: Hmm, log_likelihood: float, sequence_length: int) -> ModelCriteria: ...

def to_json(hmm: Hmm) -> str: ...
def from_json(src: str) -> Hmm: ...
def save_json(hmm: Hmm, filepath: str | Path) -> None: ...
def load_json(filepath: str | Path) -> Hmm: ...
def load_hmm(filepath: str | Path) -> Hmm: ...
def save_hmm(hmm: Hmm, filepath: str | Path) -> None: ...

# =============================================================================
# Multivariate API (v4)
# =============================================================================

# MV distribution types are re-exported directly from the extension.
MVEmissionDistribution = _core.MVEmissionDistribution
DiagonalGaussian       = _core.DiagonalGaussian
FullCovGaussian        = _core.FullCovGaussian
IndependentComponents  = _core.IndependentComponents

class HmmMV(_core.HmmMV):
    """Multivariate HMM with Python-level input validation."""
    def __init__(self, num_states: int) -> None: ...
    def set_pi(self, pi) -> None: ...
    def set_trans(self, trans) -> None: ...

class MVForwardBackwardCalculator(_core.MVForwardBackwardCalculator):
    """Multivariate forward-backward calculator with automatic array coercion."""
    def __init__(self, hmm: HmmMV, observations) -> None: ...

class MVBaumWelchTrainer(_core.MVBaumWelchTrainer):
    """Multivariate Baum-Welch (EM) trainer with automatic sequence coercion."""
    def __init__(self, hmm: HmmMV, sequences) -> None: ...
    @property
    def last_log_probability(self) -> float: ...

class MVViterbiCalculator(_core.MVViterbiCalculator):
    """Multivariate Viterbi calculator with automatic array coercion."""
    def __init__(self, hmm: HmmMV, observations) -> None: ...
    @property
    def log_probability(self) -> float: ...
    def decode(self) -> NDArray[np.int64]: ...

class MVMapBaumWelchTrainer(_core.MVMapBaumWelchTrainer):
    """Multivariate MAP Baum-Welch trainer with automatic sequence coercion."""
    def __init__(self, hmm: HmmMV, sequences, pseudo_count: float = 1.0) -> None: ...
    @property
    def last_log_probability(self) -> float: ...
    @property
    def pseudo_count(self) -> float: ...
    @pseudo_count.setter
    def pseudo_count(self, value: float) -> None: ...
    def compute_log_prior(self) -> float: ...

class MVSegmentalKMeansTrainer(_core.MVSegmentalKMeansTrainer):
    """Multivariate segmental k-means trainer with automatic sequence coercion."""
    def __init__(self, hmm: HmmMV, sequences, max_iterations: int = 100) -> None: ...
    @property
    def is_terminated(self) -> bool: ...

def kmeans_init(hmm: HmmMV, sequences, seed: int = 42) -> None: ...
def to_json_mv(hmm: HmmMV) -> str: ...
def from_json_mv(src: str) -> HmmMV: ...
def save_json_mv(hmm: HmmMV, filepath: str | Path) -> None: ...
def load_json_mv(filepath: str | Path) -> HmmMV: ...
def count_free_parameters_mv(hmm: HmmMV) -> int: ...

__all__: list[str]
