from typing import Any

class EmissionDistribution:
    def pdf(self, x: float) -> float: ...
    def log_pdf(self, x): ...
    def fit(self, data): ...
    def fit_weighted(self, data, weights): ...
    def reset(self) -> None: ...
    @property
    def is_discrete(self) -> bool: ...

class Discrete(EmissionDistribution): ...
class Binomial(EmissionDistribution): ...
class NegativeBinomial(EmissionDistribution): ...
class Poisson(EmissionDistribution): ...
class Gaussian(EmissionDistribution): ...
class Exponential(EmissionDistribution): ...
class Gamma(EmissionDistribution): ...
class LogNormal(EmissionDistribution): ...
class Pareto(EmissionDistribution): ...
class Beta(EmissionDistribution): ...
class Uniform(EmissionDistribution): ...
class Weibull(EmissionDistribution): ...
class Rayleigh(EmissionDistribution): ...
class StudentT(EmissionDistribution): ...
class ChiSquared(EmissionDistribution): ...

class Hmm:
    def __init__(self, num_states: int): ...
    @property
    def num_states(self) -> int: ...
    def validate(self) -> None: ...
    def set_pi(self, pi) -> None: ...
    def get_pi(self): ...
    def set_trans(self, trans) -> None: ...
    def get_trans(self): ...
    def set_distribution(self, state: int, distribution: EmissionDistribution) -> None: ...
    def get_distribution(self, state: int) -> EmissionDistribution: ...
    def get_distribution_name(self, state: int) -> str: ...

class ForwardBackwardCalculator:
    def __init__(self, hmm: Hmm, observations): ...
    def compute(self, observations=None) -> None: ...
    @property
    def log_probability(self) -> float: ...
    @property
    def probability(self) -> float: ...
    def get_log_forward_variables(self): ...
    def get_log_backward_variables(self): ...
    @property
    def num_states(self) -> int: ...

class ViterbiCalculator:
    def __init__(self, hmm: Hmm, observations): ...
    def decode(self): ...
    @property
    def log_probability(self) -> float: ...
    def get_state_sequence(self): ...
    @property
    def num_states(self) -> int: ...

class TrainingConfig:
    convergence_tolerance: float
    max_iterations: int
    convergence_window: int
    enable_progress_reporting: bool

class BaumWelchTrainer:
    def __init__(self, hmm: Hmm, sequences): ...
    def train(self) -> None: ...

class ViterbiTrainer:
    def __init__(self, hmm: Hmm, sequences, config: TrainingConfig = ...): ...
    def train(self) -> None: ...
    @property
    def has_converged(self) -> bool: ...
    @property
    def reached_max_iterations(self) -> bool: ...
    @property
    def last_log_probability(self) -> float: ...
    @property
    def config(self) -> TrainingConfig: ...
    @config.setter
    def config(self, value: TrainingConfig) -> None: ...

class SegmentalKMeansTrainer:
    def __init__(self, hmm: Hmm, sequences): ...
    def train(self) -> None: ...
    @property
    def is_terminated(self) -> bool: ...

def training_preset_fast() -> TrainingConfig: ...
def training_preset_balanced() -> TrainingConfig: ...
def training_preset_precise() -> TrainingConfig: ...
def load_hmm(filepath: str): ...
def save_hmm(hmm: Hmm, filepath: str) -> None: ...
