import numpy as np
from numpy.typing import NDArray

class EmissionDistribution:
    def pdf(self, x: float) -> float: ...
    def log_pdf(self, x: float | NDArray[np.float64]) -> float | NDArray[np.float64]: ...
    def fit(self, data: NDArray[np.float64]) -> None: ...
    def fit_weighted(self, data: NDArray[np.float64], weights: NDArray[np.float64]) -> None: ...
    def reset(self) -> None: ...
    @property
    def is_discrete(self) -> bool: ...

class Discrete(EmissionDistribution):
    def __init__(self, num_symbols: int = 10) -> None: ...
    def set_probability(self, index: int, value: float) -> None: ...
    def get_symbol_probability(self, index: int) -> float: ...
    @property
    def num_symbols(self) -> int: ...
    @property
    def mode(self) -> int: ...

class Binomial(EmissionDistribution):
    def __init__(self, n: int = 10, p: float = 0.5) -> None: ...
    @property
    def n(self) -> int: ...
    @n.setter
    def n(self, value: int) -> None: ...
    @property
    def p(self) -> float: ...
    @p.setter
    def p(self, value: float) -> None: ...

class NegativeBinomial(EmissionDistribution):
    def __init__(self, r: float = 5.0, p: float = 0.5) -> None: ...
    @property
    def r(self) -> float: ...
    @r.setter
    def r(self, value: float) -> None: ...
    @property
    def p(self) -> float: ...
    @p.setter
    def p(self, value: float) -> None: ...

class Poisson(EmissionDistribution):
    def __init__(self, lam: float = 1.0) -> None: ...
    @property
    def lam(self) -> float: ...
    @lam.setter
    def lam(self, value: float) -> None: ...
    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...

class Gaussian(EmissionDistribution):
    def __init__(self, mu: float = 0.0, sigma: float = 1.0) -> None: ...
    @property
    def mu(self) -> float: ...
    @mu.setter
    def mu(self, value: float) -> None: ...
    @property
    def sigma(self) -> float: ...
    @sigma.setter
    def sigma(self, value: float) -> None: ...
    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def std(self) -> float: ...
    def cdf(self, x: float) -> float: ...

class Exponential(EmissionDistribution):
    def __init__(self, lam: float = 1.0) -> None: ...
    @property
    def lam(self) -> float: ...
    @lam.setter
    def lam(self, value: float) -> None: ...
    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def std(self) -> float: ...
    def cdf(self, x: float) -> float: ...

class Gamma(EmissionDistribution):
    def __init__(self, k: float = 1.0, theta: float = 1.0) -> None: ...
    @property
    def k(self) -> float: ...
    @k.setter
    def k(self, value: float) -> None: ...
    @property
    def theta(self) -> float: ...
    @theta.setter
    def theta(self, value: float) -> None: ...
    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def std(self) -> float: ...
    def cdf(self, x: float) -> float: ...

class LogNormal(EmissionDistribution):
    """Log-normal distribution.

    ``mu`` and ``sigma`` are the log-space parameters (not the distribution mean/std).
    Use ``distribution_mean`` for E[X] = exp(mu + sigma^2/2).
    """
    def __init__(self, mu: float = 0.0, sigma: float = 1.0) -> None: ...
    @property
    def mu(self) -> float: ...
    @mu.setter
    def mu(self, value: float) -> None: ...
    @property
    def sigma(self) -> float: ...
    @sigma.setter
    def sigma(self, value: float) -> None: ...
    @property
    def distribution_mean(self) -> float: ...
    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def std(self) -> float: ...

class Pareto(EmissionDistribution):
    def __init__(self, k: float = 1.0, xm: float = 1.0) -> None: ...
    @property
    def k(self) -> float: ...
    @k.setter
    def k(self, value: float) -> None: ...
    @property
    def xm(self) -> float: ...
    @xm.setter
    def xm(self, value: float) -> None: ...

class Beta(EmissionDistribution):
    def __init__(self, alpha: float = 1.0, beta: float = 1.0) -> None: ...
    @property
    def alpha(self) -> float: ...
    @alpha.setter
    def alpha(self, value: float) -> None: ...
    @property
    def beta(self) -> float: ...
    @beta.setter
    def beta(self, value: float) -> None: ...

class Uniform(EmissionDistribution):
    def __init__(self, a: float = 0.0, b: float = 1.0) -> None: ...
    @property
    def a(self) -> float: ...
    @a.setter
    def a(self, value: float) -> None: ...
    @property
    def b(self) -> float: ...
    @b.setter
    def b(self, value: float) -> None: ...
    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    def cdf(self, x: float) -> float: ...

class Weibull(EmissionDistribution):
    def __init__(self, k: float = 1.0, lam: float = 1.0) -> None: ...
    @property
    def k(self) -> float: ...
    @k.setter
    def k(self, value: float) -> None: ...
    @property
    def lam(self) -> float: ...
    @lam.setter
    def lam(self, value: float) -> None: ...
    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    def cdf(self, x: float) -> float: ...

class Rayleigh(EmissionDistribution):
    def __init__(self, sigma: float = 1.0) -> None: ...
    @property
    def sigma(self) -> float: ...
    @sigma.setter
    def sigma(self, value: float) -> None: ...
    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    def cdf(self, x: float) -> float: ...

class StudentT(EmissionDistribution):
    def __init__(self, nu: float = ..., location: float = ..., scale: float = ...) -> None: ...
    @property
    def nu(self) -> float: ...
    @nu.setter
    def nu(self, value: float) -> None: ...
    @property
    def location(self) -> float: ...
    @location.setter
    def location(self, value: float) -> None: ...
    @property
    def scale(self) -> float: ...
    @scale.setter
    def scale(self, value: float) -> None: ...
    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def std(self) -> float: ...
    def cdf(self, x: float) -> float: ...

class ChiSquared(EmissionDistribution):
    def __init__(self, k: float = 1.0) -> None: ...
    @property
    def k(self) -> float: ...
    @k.setter
    def k(self, value: float) -> None: ...
    @property
    def mean(self) -> float: ...
    @property
    def variance(self) -> float: ...
    @property
    def std(self) -> float: ...
    def cdf(self, x: float) -> float: ...

class Hmm:
    def __init__(self, num_states: int) -> None: ...
    @property
    def num_states(self) -> int: ...
    def validate(self) -> None: ...
    def set_pi(self, pi: NDArray[np.float64]) -> None: ...
    def get_pi(self) -> NDArray[np.float64]: ...
    def set_trans(self, trans: NDArray[np.float64]) -> None: ...
    def get_trans(self) -> NDArray[np.float64]: ...
    def set_distribution(self, state: int, distribution: EmissionDistribution) -> None: ...
    def get_distribution(self, state: int) -> EmissionDistribution: ...
    def get_distribution_name(self, state: int) -> str: ...

class ForwardBackwardCalculator:
    def __init__(self, hmm: Hmm, observations: NDArray[np.float64]) -> None: ...
    def compute(self, observations: NDArray[np.float64] | None = None) -> None: ...
    @property
    def log_probability(self) -> float: ...
    @property
    def probability(self) -> float: ...
    def get_log_forward_variables(self) -> NDArray[np.float64]: ...
    def get_log_backward_variables(self) -> NDArray[np.float64]: ...
    @property
    def num_states(self) -> int: ...

class ViterbiCalculator:
    def __init__(self, hmm: Hmm, observations: NDArray[np.float64]) -> None: ...
    def decode(self) -> NDArray[np.int64]: ...
    @property
    def log_probability(self) -> float: ...
    def get_state_sequence(self) -> NDArray[np.int64]: ...
    @property
    def num_states(self) -> int: ...

class TrainingConfig:
    convergence_tolerance: float
    max_iterations: int
    convergence_window: int
    enable_progress_reporting: bool

class BaumWelchTrainer:
    def __init__(self, hmm: Hmm, sequences: list[NDArray[np.float64]]) -> None: ...
    def train(self) -> None: ...

class ViterbiTrainer:
    def __init__(self, hmm: Hmm, sequences: list[NDArray[np.float64]], config: TrainingConfig = ...) -> None: ...
    def train(self) -> None: ...
    @property
    def has_converged(self) -> bool: ...
    @property
    def reached_max_iterations(self) -> bool: ...
    @property
    def last_log_probability(self) -> float: ...
    @property
    def config(self) -> TrainingConfig: ...
    @config.setter
    def config(self, value: TrainingConfig) -> None: ...

class SegmentalKMeansTrainer:
    def __init__(self, hmm: Hmm, sequences: list[NDArray[np.float64]]) -> None: ...
    def train(self) -> None: ...
    @property
    def is_terminated(self) -> bool: ...

def training_preset_fast() -> TrainingConfig: ...
def training_preset_balanced() -> TrainingConfig: ...
def training_preset_precise() -> TrainingConfig: ...
def load_hmm(filepath: str) -> Hmm: ...
def save_hmm(hmm: Hmm, filepath: str) -> None: ...
